theme: jekyll-theme-architect
title: '<span class="LaTeX">L<sup>a</sup>T<sub>e</sub>X</span> Book Tutorial'
description: 'A tutorial for building a printable book in <span class="LaTeX">L<sup>e</sup>T<sub>e</sub>X</span>'
